Repository brenno263/se339-essay-4-faker, pull requests merged in 2022-12, with the labels that each got.

#8 Update Present.md
  present.md
Labels: documentation, good first issue

#16 Wright/present - updates
  present.md
Labels: bug, good first issue, invalid, wontfix

#17 Wrote up a conclusion
  Conclusion.md
Labels: good first issue
